Repository mauricioirace/lumino-tests, pull requests merged in 2021-05, with the labels that each got.

#4 RLP-1041: test cases improvement
  src/channel-manager/index.ts
  src/util/token.ts
  test/cases/bootstrapping.test.ts
  test/cases/channels.test.ts
  test/cases/mediated.test.ts
  test/cases/p2p.test.ts
  test/cases/payments.test.ts
  test/utils/index.ts
  topologies/advanced.json
  topologies/basic.json
  topologies/mediated.json
  topologies/p2p.json
Labels: refactor

#7 Feature/rlp 1089/format fix
  .husky/.gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc.json5
  jest-log.config.ts
  jest.config.js
  package.json
  src/channel-manager/index.ts
  src/container-manager/index.ts
  src/environment-loader/index.ts
  src/index.ts
  src/lumino-client/index.ts
  src/types/lumino-test-environment.ts
  src/types/node.ts
  src/types/wait.ts
  src/util/collection.ts
  src/util/token.ts
  test/cases/bootstrapping.test.ts
  test/cases/channels.test.ts
  test/cases/mediated.test.ts
  test/cases/p2p.test.ts
  test/setup.ts
  test/utils/index.ts
  topologies/advanced.json
  topologies/basic.json
  topologies/mediated.json
  topologies/no-channels.json
  topologies/p2p.json
  types/lumino-js-sdk.d.ts
Labels: enhancement

#8 Feature/rlp 1083/reboot and dependencies
  .gitignore
  .prettierignore
  README.md
  generateImages
  package.json
  scripts/clean
  scripts/runTests
  scripts/validateResources
Labels: enhancement

#11 Increase timeouts as temporary fix
  src/types/wait.ts
  test/cases/bootstrapping.test.ts
  test/common/index.ts
Labels: bug

#9 Feature/rlp 1086/remove sleep
  test/cases/channel/close.test.ts
  test/cases/channel/deposit.test.ts
  test/cases/channel/open.test.ts
  test/cases/payments/mediated.test.ts
  test/cases/payments/p2p.test.ts
  test/common/index.ts
  test/utils/assertions.ts
  test/utils/index.ts
  types/lumino-js-sdk.d.ts
Labels: enhancement

#10 Feature/rlp 1084/topologies
  src/channel-manager/index.ts
  src/environment-loader/index.ts
  src/types/lumino-test-environment.ts
  src/types/node.ts
  test/cases/bootstrapping.test.ts
  test/cases/channel/close.test.ts
  test/cases/channel/deposit.test.ts
  test/cases/channel/open.test.ts
  test/cases/payments/mediated.test.ts
  test/cases/payments/p2p.test.ts
  test/utils/index.ts
  topologies/advanced.json
  topologies/mediated.json
  topologies/no-channels.json
  topologies/p2p.json
Labels: enhancement
